fn main() -> Result<(), anyhow::Error> {
    let input = std::fs::read_to_string("packages/aoc_2025_7/input.txt")
        .expect("Failed to read input file");

    let _parsed = parse(&input)?;
    Ok(())
}

fn parse(s: &str) -> Result<Vec<&str>, anyhow::Error> {
    Ok(s.lines().rev().collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    const INPUT: &str = ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
";

    #[test]
    fn it_parses() -> Result<(), anyhow::Error> {
        parse(INPUT)?;
        Ok(())
    }
}
